GET http://localhost:3000/productos?category=men's clothing


### de 
POST http://localhost:3000/productos
Content-Type: application/json

{
    "title": "Producto 1",
    "price": 100,
    "description": "Descripcion del producto 1",
    "category": "men's clothing",
    "image": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg"
}
